sudo: required
services:
  - docker
before_install:
  - docker build -t docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-430990616580"
  bucket_path: "docker-test"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
