version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/service/node_modules
      - .:/usr/src/service
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/src/service/node_modules
      - .:/usr/src/service
    command: ["npm", "run", "test"]
    